POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVtYWlsMkBlbWFpbC5jb20iLCJleHAiOjE3MDg3NDY1NzksInVzZXJJZCI6Mn0.SFQ2O2598D5y0UWd96df3o4_b3PKM6FxI6K0echXiVo

{
  "name": "Aniversário",
  "description": "Celebração do aniversário de alguém",
  "location": "Local da festa",
  "datetime": "2024-02-16T15:30:00Z"
}
